- name: Install Java
  yum:
    state: latest
    name: openjdk-Java

- name: Download tomcat 8
  get_url:
     url: {{ Tomcat_URL }}
     dest: /opt/  
     
- name: Extract tomcat to /opt
  unarchive:
      src: {{ Tomcat_ZIP }}
      dest: /opt/

- name: start service
  shell: /opt/{{Tomcat_Name}}/bin/catalina.sh start 
     